### ISSUE TITLE
我不确定驱动是否安装正确了但usb似乎只能放电

### ISSUE THREAD

**Issue by Yty202020** [qaz6750/Xiaomi9-NT-Drivers#1]
如题 我在mindows mi9 工具箱driver目录直接clone了项目 /bin/driver/cepheus/Xiaomi9-NT-Drivers 并重装了win10 相比之前的空驱动 音量+－都会触发静音提示 usb可以放电了 但仍不可typec/拓展坞连接键鼠 请问我操作是否正确么 或需要什么编译之类的
本人web/unity+java/php/python 全栈开发 但不擅长硬件方面 对此项目很感兴趣 请大佬们指导

**Comment by qaz6750** [comment]
是的，如你所看到的，USB依然有问题，因为目前可以左键的触摸的UEFI尚未公布，所以不能使用触摸

**Comment by Yty202020** [comment]
哦哦 谢谢 会持续关注您的项目&nbsp;我去试试把mi mix2s 或mi pad5的usb驱动合并到您的项目会不会有惊喜&nbsp;


回到未来
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qaz6750 ***@***.***&gt;; 
发送时间: 2023年1月20日(星期五) 中午12:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qaz6750/Xiaomi9-NT-Drivers] 我不确定驱动是否安装正确了但usb似乎只能放电 (Issue #1)





 
是的，如你所看到的，USB依然有问题，因为目前可以左键的触摸的UEFI尚未公布，所以不能使用触摸

**Comment by qaz6750** [comment]
我警告：请不要使用845平台的任何驱动，pad5的驱动和现在米9的同源

**Comment by Yty202020** [comment]
copy



---原始邮件---
发件人: "qaz6750 ***@***.***&gt;
发送时间: 2023年1月20日(周五) 中午12:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qaz6750/Xiaomi9-NT-Drivers] 我不确定驱动是否安装正确了但usb似乎只能放电 (Issue #1)




 
我警告：请不要使用845平台的任何驱动，pad5的驱动和现在米9的同源
