### ISSUE TITLE
[Panelcfg]由于更换屏幕所导致的面板问题

### ISSUE THREAD

**Issue by 4455jkjh** [qaz6750/Xiaomi9-NT-Drivers#3]
装了GPU驱动后屏幕会变暗，禁用GPU重启正常启用GPU又会变暗

**Comment by qaz6750** [comment]
我建议使用其他版本重新安装测试，我使用[DriverUpdater](https://github.com/WOA-Project/DriverUpdater)没有出现这类问题

**Comment by qaz6750** [comment]
使用DriverUpdater的说明，很快会添加

**Comment by 4455jkjh** [comment]
好的

**Comment by 4455jkjh** [comment]
我试过win11 22621, 25276, 22598,驱动也试过1.0.0-beta1和main分支,使用DriverUpdater安装的，还是没有解决,不知道是不是跟我换过屏幕有关

**Comment by qaz6750** [comment]
大概率可能是。其他人都没有出现这类问题...

**Comment by Yty202020** [comment]
我用mindows装的驱动包 也是main和release都试了下
感觉刚开始那个古诗句界面过度到设置的windows动画很卡  但屏幕未变暗 不知道是不是gpu未工作

**Comment by 4455jkjh** [comment]
> 我用mindows装的驱动包 也是main和release都试了下 感觉刚开始那个古诗句界面过度到设置的windows动画很卡 但屏幕未变暗 不知道是不是gpu未工作

转到 "设置"->"系统"->"屏幕"->"高级显示器设置" 如果显示器1连接到'MI9 Adreno 640 '说明GPU已驱动
![IMG_20230129_114329](https://user-images.githubusercontent.com/12042643/215303683-2e27ed33-3a36-4de6-bce6-6fc3c3f6b3ab.jpg)
![IMG_20230129_114039](https://user-images.githubusercontent.com/12042643/215303684-641d91be-3988-40a6-86ea-089034d212a7.jpg)

**Comment by Yty202020** [comment]
额 您是如何操作的 我的touch还是不能用 目前usbfn only 难道要用driverUpdater安装？

**Comment by 4455jkjh** [comment]
> 额 您是如何操作的 我的touch还是不能用 目前usbfn only 难道要用driverUpdater安装？

DriverUpdater, Mindows的UEFI可能不是最新的，我自己编译的UEFI

**Comment by Yty202020** [comment]
蟹蟹 我去试试😀

**Comment by qaz6750** [comment]
- Mindows的UEFI已经更新到最新
- 请使用DriverUpdater进行安装驱动
- USB状态如表，USBfn指的是充电状态，目前上游驱动依然不完善，无法切换到usbhost进行鼠标或者U盘

**Comment by qaz6750** [comment]
> > 我用mindows装的驱动包 也是main和release都试了下 感觉刚开始那个古诗句界面过度到设置的windows动画很卡 但屏幕未变暗 不知道是不是gpu未工作
> 
> 转到 "设置"->"系统"->"屏幕"->"高级显示器设置" 如果显示器1连接到'MI9 Adreno 640 '说明GPU已驱动 ![IMG_20230129_114329](https://user-images.githubusercontent.com/12042643/215303683-2e27ed33-3a36-4de6-bce6-6fc3c3f6b3ab.jpg) ![IMG_20230129_114039](https://user-images.githubusercontent.com/12042643/215303684-641d91be-3988-40a6-86ea-089034d212a7.jpg)

* 如果方便请回到安装使用“隐秘参数”并打开root模式，帮助我进行确定面板问题

**Comment by 4455jkjh** [comment]
![Screenshot_2023-01-29-13-51-34-126_com x1y9 probe](https://user-images.githubusercontent.com/12042643/215307864-eb5d3970-6fbc-4983-94b8-50167b2e33b7.jpg)

**Comment by qaz6750** [comment]
* 你的面板为dsi-panel-samsung-fhd-ea8076-f1p2-cmd
* 目前适配的是dsi-panel-samsung-fhd-ea8076-f1mp-cmd面板，有一些不同，在考虑如何解决面板问题

**Comment by 4455jkjh** [comment]
谢谢

**Comment by qaz6750** [comment]
* 请按照我的邮箱联系我的QQ，单独适配

**Comment by qaz6750** [comment]
* https://github.com/qaz6750/Xiaomi9-NT-Drivers/commit/21e64fc84597ab1c4cdfe765a4890021f7ae30ca This problem has been fixed through brightness control
